/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buscardatosmercado;

import java.awt.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;
import java.util.List;


/**
 *
 * @author Max
 */
public class vista extends javax.swing.JFrame {
    
    private static final String CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTMHHl9BoAA1bdi300FS-3sICRwHo8j_6u5bFCOUp-NB7nXMO0ttmUdR-eyltzk0w/pub?output=csv";
    private List<String[]> data;

    public vista() {
        initComponents();// Método generado automáticamente
        configurarTabla(); // Configuraciones adicionales para la tabla
        cargarDatosCSV();  // Cargar datos al iniciar la vista
        
        // Cambiar el color de fondo del JFrame
        getContentPane().setBackground(new Color(17, 122, 101));
        
        // Añadir el KeyListener para detectar Enter en el campo de búsqueda
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    jButton1.doClick();  // Simula un click en el botón
                }
            }
        });
    }
    
    public class NonReorderableTableColumnModel extends DefaultTableColumnModel {
        @Override
        public void moveColumn(int columnIndex, int newIndex) {
            // Sobreescribe el método para evitar el reordenamiento
        }
    }
    
    private void configurarTabla() {
        DefaultTableModel modeloNoEditable = new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
            },
            new String [] {
                "NOMBRES Y APELLIDOS", "PAB", "PUESTO", "N°DNI", "Mercado", "PAGO 2022", "PAGÓ 2023", "PAGO 2024"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;  // Hace que ninguna celda sea editable
            }
        };
        
        jTable1.setModel(modeloNoEditable);
        
        // Ajustar el ancho de las columnas
        TableColumnModel columnModel = new NonReorderableTableColumnModel();
        for (int i = 0; i < modeloNoEditable.getColumnCount(); i++) {
            TableColumn column = new TableColumn(i);
            column.setHeaderValue(modeloNoEditable.getColumnName(i));
            column.setPreferredWidth(100);  // Ajusta el ancho inicial si es necesario
            columnModel.addColumn(column);
        }
        jTable1.setColumnModel(columnModel);
        
        // Ajustar el ancho de las columnas
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(240); // NOMBRES Y APELLIDOS
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(40); // PAB
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(40); // PUESTO
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40); // N°DNI
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(140); // Mercado
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(50); // PAGO 2022
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(50); // PAGÓ 2023
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(50); // PAGO 2024
        
        jScrollPane1.setViewportView(jTable1);
    }
    
    private void cargarDatosCSV() {
        data = CSVReaderExample.readCSV(CSV_URL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setIconImages(getIconImages());

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo SM  actual 2023-2026(4).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escudooo san(1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese su Busqueda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(548, 548, 548)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String query = jTextField1.getText().trim(); // Obtener el texto ingresado
        if (!query.isEmpty()) {
            List<String[]> resultados;
            if (query.matches("\\d+")) { // Si la consulta es un número, buscar por DNI
                resultados = CSVReaderExample.buscarPorDNI(data, query);
            } else { // Si no es un número, buscar por nombre
                resultados = CSVReaderExample.buscarPorNombre(data, query);
            }
            mostrarResultadosEnTabla(resultados);  // Mostrar los resultados en la tabla
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Mostrar los resultados en la tabla
    private void mostrarResultadosEnTabla(List<String[]> resultados) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar tabla
        for (String[] fila : resultados) {
            model.addRow(new Object[]{fila[0], fila[1], fila[2], fila[3], fila[4], fila[5], fila[6], fila[7]});  // Añadir los datos a la tabla
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
